name: nyc_analytics
version: 1.0.0
config-version: 2
profile: default
model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots
target-path: target
clean-targets:
  - target
  - dbt_packages
models:
  nyc_analytics:
    +materialized: table
    staging:
      +materialized: table
      +schema: staging__nyc_311_street_complaint_motor_vehicle_crash_dataset
    marts:
      +materialized: table
      +schema: staging__nyc_311_street_complaint_motor_vehicle_crash_dataset
      shared:
        +materialized: table